### ISSUE TITLE
where to find each epoch's error and draw the graph

### ISSUE THREAD

**Issue by mit10000** [hysts/pytorch_image_classification#1]
Thanks hysts for sharing the package.
One question is where can I find the error rate of each epoch?

**Comment by hysts** [comment]
To dump scalars to a file, you need to install `tensorboardX` and use `--tensorboard` option. With the flag, all the scalars reported to Tensorboard are dumped to a file `all_scalars.json` in the output directory you specified with `--outdir` option after training finishes. Error rate itself is not dumped, but since `error rate = 1 - accuracy`, you can plot it using `Test/Accuracy` dumped in `all_scalars.json`.

**Comment by hysts** [comment]
Hmmm... It seems `tensorboardX` doesn't dump all scalars anymore if you use `add_scalar`. See https://github.com/lanpa/tensorboardX/issues/135. 
You can still extract scalars from the log file of `tensorboardX`. See https://stackoverflow.com/a/52756780.
